-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: 0ff8620e03bf7acfb4dfdc86de14baf032c604f5
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
    -   id: check-case-conflict
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: detect-private-key
-   repo: https://github.com/pricematch/pricematch-pre-commit-hooks
    sha: 751a6d417bc6647552c31b051ed2586eacd460b1
    hooks:
    -   id: do_not_commit
-   repo: https://github.com/AStrangerGravity/pre-commit-hooks
    sha: dd9237660cdbeb22fb8fb0bfa18d5d625e717ab4
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: forbid-tabs
    -   id: remove-tabs
        args:
        - --whitespaces-count=2
